graph LR
    BUNDLE[Bundle<br/>Source Code]
    SYNTH[Synthesize<br/>CloudFormation Template]
    DEPLOY[Deploy<br/>Assets]
    APPLY[Apply<br/>CloudFormation Template]
    BUNDLE-->SYNTH-->DEPLOY-->APPLY